{% set name = "tootapari" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tootapari-{{ version }}.tar.gz
  sha256: 0b529f8584dd0e2ff748a7b54dd6e5dea5a37d8324f0a0861c84dd834f8b50ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - appdirs
    - mastodon.py
    - napari
    - numpy
    - python >=3.8
    - python-dotenv
    - qtpy

test:
  imports:
    - tootapari
  commands:
    - pip list
    # - pip check  # Fails due to mastodon-py
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/kephale/tootapari
  summary: A plugin to send Mastodon toots from napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kephale
